# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('butiko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
