# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('butiko', '0002_itemlist_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
