# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('butiko', '0003_auto_20160406_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='users',
            field=models.ManyToManyField(related_name='list_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
