# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butiko', '0005_auto_20160411_2116'),
        ('butiko', '0004_auto_20160411_2255'),
    ]

    operations = [
    ]
